### ISSUE TITLE
Proper usage of data types

### ISSUE THREAD

**Issue by hypervtechnics** [philvessey/NextDepartures#18]
E.g. `DepartureTime` in `Service` class.

**Comment by philvessey** [comment]
I have pushed the first part of my refactoring to use the models provided by the GTFS library. Correct data types are now used across the libraries except for DepartureTime in the Service class which I will work on now the main refactoring has been completed.

**Comment by hypervtechnics** [comment]
@philvessey Are there any problems I could help solving?

**Comment by philvessey** [comment]
I should be ok with it - I will reach out if I run into issues.

**Comment by philvessey** [comment]
I have done some more refactoring so that now the Departure and Service classes have:

public DateTime DepartureDateTime
public TimeOfDay? DepartureTime

This brings them into line with the GTFS classes using TimeOfDay and gives the user a lot more options to display the times instead of just outputting a string. I need to do some testing on it which I will do tomorrow and if all OK I will push up the changes.
